allowBuilds:
  canvas: true
  core-js: true
  protobufjs: true
  sharp: true

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fisch0920/config'
  - lqip-modern

onlyBuiltDependencies:
  - sharp
  - simple-git-hooks
